"""like, movie table 확장+불필요 테이블 삭제

Revision ID: 6498b137765c
Revises: 596ae3f62c62
Create Date: 2025-05-26 20:17:20.201870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6498b137765c'
down_revision = '596ae3f62c62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like_details')
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actors', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('movie_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('movie_type')
        batch_op.drop_column('country')
        batch_op.drop_column('actors')

    op.create_table('like_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('like_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['like_id'], ['likes.like_id'], name=op.f('like_details_like_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('like_details_pkey'))
    )
    # ### end Alembic commands ###
