"""watchlist테이블 수정

Revision ID: 40f7647c5d33
Revises: ec0fc1b58a0a
Create Date: 2025-05-27 15:31:37.409157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f7647c5d33'
down_revision = 'ec0fc1b58a0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('actors', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('movie_type', sa.String(length=50), nullable=True))
        batch_op.drop_column('notified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notified', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('movie_type')
        batch_op.drop_column('country')
        batch_op.drop_column('actors')
        batch_op.drop_column('genre')
        batch_op.drop_column('director')

    # ### end Alembic commands ###
