"""add all tables

Revision ID: 596ae3f62c62
Revises: 81ca7dca1196
Create Date: 2025-05-26 12:52:36.455010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596ae3f62c62'
down_revision = '81ca7dca1196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('movie_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('director', sa.String(length=100), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_table('recommendations',
    sa.Column('rec_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('rec_id')
    )
    op.create_table('watchlist',
    sa.Column('watch_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.String(length=50), nullable=True),
    sa.Column('movie_title', sa.String(length=200), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('watch_id')
    )
    op.create_table('like_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('like_id', sa.Integer(), nullable=False),
    sa.Column('reason_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['like_id'], ['likes.like_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like_details')
    op.drop_table('watchlist')
    op.drop_table('recommendations')
    op.drop_table('movies')
    # ### end Alembic commands ###
