"""likes 테이블 구조 변경

Revision ID: 993d4b6f9b69
Revises: 40f7647c5d33
Create Date: 2025-06-05 23:15:24.111627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993d4b6f9b69'
down_revision = '40f7647c5d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_id', sa.String(length=100), nullable=True))
        batch_op.drop_column('target_value')
        batch_op.drop_column('target_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('target_value', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('movie_id')

    # ### end Alembic commands ###
