"""like table 확장 반영

Revision ID: ec0fc1b58a0a
Revises: 6498b137765c
Create Date: 2025-05-26 20:59:57.217206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec0fc1b58a0a'
down_revision = '6498b137765c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reasons', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_column('reasons')

    # ### end Alembic commands ###
